"""Freeze one fully validated release closure."""

from __future__ import annotations

from typing import Protocol

from dlstudio.constraints.api import ConstraintSet
from dlstudio.foundation.api import BlobRef, canonical_bytes
from dlstudio.release.api import PackageFile, ReleaseCandidate
from dlstudio.rendering.api import (
    ExecutionFingerprint,
    RenderOptions,
    RenderResult,
    execution_key,
)
from dlstudio.review.api import ReviewVerdict
from dlstudio.timeline.api import (
    CheckPolicy,
    CheckReport,
    TimelineIR,
    check_timeline,
)


class BlobStore(Protocol):
    def put_bytes(self, data: bytes) -> BlobRef: ...

    def verify(self, ref: BlobRef) -> None: ...


def freeze_release(
    store: BlobStore,
    *,
    production_id: str,
    timeline: TimelineIR,
    policy: CheckPolicy,
    report: CheckReport,
    fingerprint: ExecutionFingerprint,
    options: RenderOptions,
    render: RenderResult,
    constraints: ConstraintSet,
    verdict: ReviewVerdict,
    package: tuple[PackageFile, ...],
) -> tuple[ReleaseCandidate, BlobRef]:
    """Validate exact relations once; delivery only copies the frozen package."""

    if timeline.production_id != production_id:
        raise ValueError("timeline belongs to another production")
    if constraints.production_id != production_id:
        raise ValueError("constraints belong to another production")
    if policy.constraints != constraints.ref:
        raise ValueError("check policy does not use these constraints")
    if not policy.require_approved_assets:
        raise ValueError("release policy must require approved assets")
    if not policy.require_redistributable_assets:
        raise ValueError("release policy must require redistributable assets")
    expected_report = check_timeline(timeline, policy)
    if report != expected_report or report.blocking:
        raise ValueError("release check report is stale or blocking")
    expected_key = execution_key(timeline, fingerprint, options)
    if render.cache_key != expected_key:
        raise ValueError("render execution identity does not match")
    if verdict.outcome != "pass":
        raise ValueError("release requires a passing review")
    if verdict.artifact != render.artifact:
        raise ValueError("review does not name the exact final artifact")
    if verdict.check_report != report.ref:
        raise ValueError("review does not name the exact check report")
    if verdict.constraints != constraints.ref:
        raise ValueError("review does not name the exact constraints")
    if not {"audio", "visual", "constraints"}.issubset(verdict.scope):
        raise ValueError("final review scope is incomplete")

    objects = store
    timeline_ref = objects.put_bytes(timeline.canonical_bytes())
    policy_ref = objects.put_bytes(policy.canonical_bytes())
    report_ref = objects.put_bytes(report.canonical_bytes())
    execution_ref = objects.put_bytes(fingerprint.canonical_bytes())
    options_ref = objects.put_bytes(options.canonical_bytes())
    constraints_ref = objects.put_bytes(constraints.canonical_bytes())
    verdict_ref = objects.put_bytes(verdict.canonical_bytes())
    if (
        timeline_ref != timeline.ref
        or policy_ref != policy.ref
        or report_ref != report.ref
        or execution_ref != fingerprint.ref
        or options_ref != options.ref
        or constraints_ref != constraints.ref
        or verdict_ref != verdict.ref
    ):
        raise ValueError("release input identity mismatch")

    revision_refs: list[BlobRef] = []
    licenses: list[dict[str, object]] = []
    for snapshot in timeline.assets:
        revision = snapshot.revision
        if revision.approval.status != "approved":
            raise ValueError(f"asset is not approved: {revision.asset_id}")
        if not revision.license.redistribution_allowed:
            raise ValueError(f"asset is not redistributable: {revision.asset_id}")
        revision_ref = objects.put_bytes(revision.canonical_bytes())
        if revision_ref != revision.ref.object:
            raise ValueError("asset revision identity mismatch")
        revision_refs.append(revision_ref)
        for reachable in revision.reachable_blobs:
            objects.verify(reachable)
        licenses.append(
            {
                "asset_id": revision.asset_id,
                "revision": revision_ref.as_payload(),
                "license": revision.license.as_payload(),
            }
        )

    license_raw = canonical_bytes(
        {"assets": licenses},
        domain="dlstudio.release_license_bundle",
        version=1,
    )
    license_ref = objects.put_bytes(license_raw)
    if any(item.path == "licenses.json" for item in package):
        raise ValueError("licenses.json is generated by freeze_release")
    frozen_package = (*package, PackageFile("licenses.json", license_ref))
    for item in frozen_package:
        objects.verify(item.blob)
    objects.verify(render.artifact)

    candidate = ReleaseCandidate(
        production_id=production_id,
        timeline=timeline_ref,
        check_policy=policy_ref,
        execution=execution_ref,
        render_options=options_ref,
        execution_key=expected_key,
        final_output=render.artifact,
        check_report=report_ref,
        review_verdict=verdict_ref,
        constraints=constraints_ref,
        asset_revisions=tuple(revision_refs),
        license_bundle=license_ref,
        package=frozen_package,
    )
    candidate_ref = objects.put_bytes(candidate.canonical_bytes())
    if candidate_ref != candidate.ref:
        raise ValueError("release candidate identity mismatch")
    return candidate, candidate_ref
