/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v3/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance Route */
        post: operations["advanceProduction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/blobs/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Blob */
        get: operations["getBlob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deliver */
        post: operations["deliverProduction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["submitReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BlobRef
         * @description Exact identity of immutable bytes in an object store.
         */
        BlobRef: {
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
        };
        /** DeliveryBody */
        DeliveryBody: {
            /** Destination Id */
            destination_id: string;
        };
        /** DeliveryReceipt */
        DeliveryReceipt: {
            /** Candidate Id */
            candidate_id: string;
            /** Delivered At */
            delivered_at: string;
            /** Destination Id */
            destination_id: string;
            /** Manifest */
            manifest: components["schemas"]["PackageFile"][];
        };
        /** DeliveryResponse */
        DeliveryResponse: {
            receipt: components["schemas"]["DeliveryReceipt"];
            status: components["schemas"]["WorkflowStatus"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NamedRef */
        NamedRef: {
            blob: components["schemas"]["BlobRef"];
            /** Name */
            name: string;
        };
        /** PackageFile */
        PackageFile: {
            blob: components["schemas"]["BlobRef"];
            /** Path */
            path: string;
        };
        /** ReviewFindingBody */
        ReviewFindingBody: {
            /** Finding Id */
            finding_id: string;
            /**
             * Requires Change
             * @default false
             */
            requires_change: boolean;
            /** Text */
            text: string;
        };
        /** ReviewVerdictBody */
        ReviewVerdictBody: {
            /** Findings */
            findings: components["schemas"]["ReviewFindingBody"][];
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "pass" | "changes_requested" | "block";
            /** Reviewed At */
            reviewed_at: string;
            /** Reviewer */
            reviewer: string;
            /** Scope */
            scope: string[];
        };
        /** StageAttempt */
        StageAttempt: {
            /** Error */
            error?: string | null;
            /** Inputs */
            inputs: components["schemas"]["NamedRef"][];
            /** Operation Id */
            operation_id: string;
            /**
             * Outputs
             * @default []
             */
            outputs: components["schemas"]["NamedRef"][];
            /**
             * Stage
             * @enum {string}
             */
            stage: "prepare" | "draft" | "final" | "review" | "package" | "deliver";
            /**
             * State
             * @default running
             * @enum {string}
             */
            state: "running" | "succeeded" | "failed";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkflowRun */
        WorkflowRun: {
            /**
             * Attempts
             * @default []
             */
            attempts: components["schemas"]["StageAttempt"][];
            delivery_receipt?: components["schemas"]["BlobRef"] | null;
            eligible_candidate?: components["schemas"]["BlobRef"] | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "reel" | "longform" | "capture_vo";
            /** Production Id */
            production_id: string;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Run Id */
            run_id: string;
        };
        /**
         * WorkflowStatus
         * @description Read-only application projection shared by every adapter.
         */
        WorkflowStatus: {
            /** Action */
            action: ("advance" | "review" | "deliver") | null;
            /** Completed */
            completed: boolean;
            /** Current Stage */
            current_stage: ("prepare" | "draft" | "final" | "review" | "package" | "deliver") | null;
            /** Production Id */
            production_id: string;
            /** Stage Order */
            stage_order: ("prepare" | "draft" | "final" | "review" | "package" | "deliver")[];
            workflow: components["schemas"]["WorkflowRun"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    advanceProduction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStatus"];
                };
            };
        };
    };
    getBlob: {
        parameters: {
            query: {
                size: number;
            };
            header?: never;
            path: {
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deliverProduction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewVerdictBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStatus"];
                };
            };
        };
    };
}
