/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v3/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance Route */
        post: operations["advanceProduction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/blobs/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Blob */
        get: operations["getBlob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deliver */
        post: operations["deliverProduction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["submitReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/review/artifacts/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Artifact */
        get: operations["getReviewArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/review/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Context */
        get: operations["getReviewContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/review/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Review */
        get: operations["getCurrentReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/review/task-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Task Pack */
        get: operations["getReviewTaskPack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BlobRef
         * @description Exact identity of immutable bytes in an object store.
         */
        BlobRef: {
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
        };
        /** DeliveryBody */
        DeliveryBody: {
            /** Destination Id */
            destination_id: string;
        };
        /** DeliveryReceipt */
        DeliveryReceipt: {
            /** Candidate Id */
            candidate_id: string;
            /** Delivered At */
            delivered_at: string;
            /** Destination Id */
            destination_id: string;
            /** Manifest */
            manifest: components["schemas"]["PackageFile"][];
        };
        /** DeliveryResponse */
        DeliveryResponse: {
            receipt: components["schemas"]["DeliveryReceipt"];
            status: components["schemas"]["WorkflowStatus"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NamedRef */
        NamedRef: {
            blob: components["schemas"]["BlobRef"];
            /** Name */
            name: string;
        };
        /** PackageFile */
        PackageFile: {
            blob: components["schemas"]["BlobRef"];
            /** Path */
            path: string;
        };
        /** ReviewContext */
        ReviewContext: {
            artifact: components["schemas"]["BlobRef"];
            check_report: components["schemas"]["BlobRef"];
            constraints: components["schemas"]["BlobRef"];
            /** Duration Ns */
            duration_ns: number;
            /** Fps Den */
            fps_den: number;
            /** Fps Num */
            fps_num: number;
            /** Height */
            height: number;
            /** Items */
            items: components["schemas"]["ReviewTimelineItem"][];
            latest_round: components["schemas"]["BlobRef"] | null;
            latest_verdict: components["schemas"]["ReviewVerdict"] | null;
            timeline: components["schemas"]["BlobRef"];
            /** Width */
            width: number;
        };
        /** ReviewFinding */
        ReviewFinding: {
            /** Finding Id */
            finding_id: string;
            locator?: components["schemas"]["ReviewLocator"] | null;
            /**
             * Requires Change
             * @default false
             */
            requires_change: boolean;
            /** Text */
            text: string;
        };
        /** ReviewFindingBody */
        ReviewFindingBody: {
            /** Finding Id */
            finding_id: string;
            locator?: components["schemas"]["ReviewLocatorBody"] | null;
            /**
             * Requires Change
             * @default false
             */
            requires_change: boolean;
            /** Text */
            text: string;
        };
        /**
         * ReviewLocator
         * @description Frame-accurate location plus optional spatial and timeline targets.
         */
        ReviewLocator: {
            /** End Frame Exclusive */
            end_frame_exclusive: number;
            region?: components["schemas"]["ReviewRegion"] | null;
            /** Start Frame */
            start_frame: number;
            /**
             * Target Ids
             * @default []
             */
            target_ids: string[];
        };
        /** ReviewLocatorBody */
        ReviewLocatorBody: {
            /** End Frame Exclusive */
            end_frame_exclusive: number;
            region?: components["schemas"]["ReviewRegionBody"] | null;
            /** Start Frame */
            start_frame: number;
            /** Target Ids */
            target_ids?: string[];
        };
        /**
         * ReviewRegion
         * @description Normalized 0..1000 rectangle inside the reviewed frame.
         */
        ReviewRegion: {
            /** Height Milli */
            height_milli: number;
            /** Width Milli */
            width_milli: number;
            /** X Milli */
            x_milli: number;
            /** Y Milli */
            y_milli: number;
        };
        /** ReviewRegionBody */
        ReviewRegionBody: {
            /** Height Milli */
            height_milli: number;
            /** Width Milli */
            width_milli: number;
            /** X Milli */
            x_milli: number;
            /** Y Milli */
            y_milli: number;
        };
        /**
         * ReviewResolution
         * @description Typed resolution of one required finding from the previous round.
         */
        ReviewResolution: {
            /** Current Finding Id */
            current_finding_id?: string | null;
            /** Previous Finding Id */
            previous_finding_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "fixed" | "obsolete" | "still_wrong";
        };
        /** ReviewResolutionBody */
        ReviewResolutionBody: {
            /** Current Finding Id */
            current_finding_id?: string | null;
            /** Previous Finding Id */
            previous_finding_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "fixed" | "obsolete" | "still_wrong";
        };
        /**
         * ReviewRound
         * @description Immutable link between an exact verdict and its previous review.
         */
        ReviewRound: {
            previous_round?: components["schemas"]["BlobRef"] | null;
            /**
             * Resolutions
             * @default []
             */
            resolutions: components["schemas"]["ReviewResolution"][];
            verdict: components["schemas"]["BlobRef"];
        };
        /** ReviewSourceMapping */
        ReviewSourceMapping: {
            /**
             * Status
             * @default unavailable
             * @constant
             */
            status: "unavailable";
        };
        /** ReviewTaskPack */
        ReviewTaskPack: {
            artifact: components["schemas"]["BlobRef"];
            check_report: components["schemas"]["BlobRef"];
            constraints: components["schemas"]["BlobRef"];
            /** Duration Ns */
            duration_ns: number;
            /** Fps Den */
            fps_den: number;
            /** Fps Num */
            fps_num: number;
            /** Height */
            height: number;
            latest_round: components["schemas"]["BlobRef"];
            review_round: components["schemas"]["ReviewRound"];
            source_mapping: components["schemas"]["ReviewSourceMapping"];
            /** Target Snapshots */
            target_snapshots: components["schemas"]["ReviewTimelineItem"][];
            timeline: components["schemas"]["BlobRef"];
            verdict: components["schemas"]["ReviewVerdict"];
            verdict_ref: components["schemas"]["BlobRef"];
            /** Width */
            width: number;
        };
        /** ReviewTimelineItem */
        ReviewTimelineItem: {
            /** Duration Ns */
            duration_ns: number;
            /** Item Id */
            item_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "visual" | "audio" | "transition";
            /** Label */
            label: string;
            /** Lane */
            lane: string;
            /** Start Ns */
            start_ns: number;
            /** Z */
            z?: number | null;
        };
        /** ReviewVerdict */
        ReviewVerdict: {
            artifact: components["schemas"]["BlobRef"];
            check_report: components["schemas"]["BlobRef"];
            constraints: components["schemas"]["BlobRef"];
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["BlobRef"][];
            /**
             * Findings
             * @default []
             */
            findings: components["schemas"]["ReviewFinding"][];
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "pass" | "changes_requested" | "block";
            review_pack?: components["schemas"]["BlobRef"] | null;
            /** Reviewed At */
            reviewed_at: string;
            /** Reviewer */
            reviewer: string;
            /** Scope */
            scope: string[];
        };
        /** ReviewVerdictBody */
        ReviewVerdictBody: {
            expected_artifact: components["schemas"]["BlobRef"];
            expected_check_report: components["schemas"]["BlobRef"];
            expected_constraints: components["schemas"]["BlobRef"];
            expected_latest_round?: components["schemas"]["BlobRef"] | null;
            expected_timeline: components["schemas"]["BlobRef"];
            /** Findings */
            findings: components["schemas"]["ReviewFindingBody"][];
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "pass" | "changes_requested" | "block";
            /** Resolutions */
            resolutions?: components["schemas"]["ReviewResolutionBody"][];
            /** Reviewed At */
            reviewed_at: string;
            /** Reviewer */
            reviewer: string;
            /** Scope */
            scope: string[];
        };
        /** StageAttempt */
        StageAttempt: {
            /** Error */
            error?: string | null;
            /** Inputs */
            inputs: components["schemas"]["NamedRef"][];
            /** Operation Id */
            operation_id: string;
            /**
             * Outputs
             * @default []
             */
            outputs: components["schemas"]["NamedRef"][];
            /**
             * Stage
             * @enum {string}
             */
            stage: "prepare" | "draft" | "final" | "review" | "package" | "deliver";
            /**
             * State
             * @default running
             * @enum {string}
             */
            state: "running" | "succeeded" | "failed";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkflowRun */
        WorkflowRun: {
            /**
             * Attempts
             * @default []
             */
            attempts: components["schemas"]["StageAttempt"][];
            delivery_receipt?: components["schemas"]["BlobRef"] | null;
            eligible_candidate?: components["schemas"]["BlobRef"] | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "reel" | "longform" | "capture_vo";
            /** Production Id */
            production_id: string;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Run Id */
            run_id: string;
        };
        /**
         * WorkflowStatus
         * @description Read-only application projection shared by every adapter.
         */
        WorkflowStatus: {
            /** Action */
            action: ("advance" | "review" | "deliver") | null;
            /** Completed */
            completed: boolean;
            /** Current Stage */
            current_stage: ("prepare" | "draft" | "final" | "review" | "package" | "deliver") | null;
            /** Production Id */
            production_id: string;
            /** Stage Order */
            stage_order: ("prepare" | "draft" | "final" | "review" | "package" | "deliver")[];
            workflow: components["schemas"]["WorkflowRun"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    advanceProduction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStatus"];
                };
            };
        };
    };
    getBlob: {
        parameters: {
            query: {
                size: number;
            };
            header?: never;
            path: {
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deliverProduction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewVerdictBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getReviewArtifact: {
        parameters: {
            query: {
                size: number;
            };
            header?: never;
            path: {
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "video/mp4": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getReviewContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewContext"];
                };
            };
        };
    };
    getCurrentReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewVerdict"];
                };
            };
        };
    };
    getReviewTaskPack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewTaskPack"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStatus"];
                };
            };
        };
    };
}
